services:
  vllm-gpt-oss-20b:
    image: vllm/vllm-openai:v0.11.0-x86_64
    container_name: vllm-gpt-oss-20b
    restart: unless-stopped
    command: >
      --model openai/gpt-oss-20b
      --gpu-memory-utilization 0.80
      --max-model-len 128k
      --max-num-batched-tokens 30k
      --tensor-parallel-size 2
      --enable-sleep-mode
      --enable-auto-tool-choice
      --tool-call-parser openai
    ports:
      - "8002:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - VLLM_SERVER_DEV_MODE=1
      - CUDA_VISIBLE_DEVICES=0,1
      - VLLM_HOST_IP=127.0.0.1
    ipc: host
    networks:
      - homegpt-network
