services:
  vllm-qwen3-next-80b-a3b-thinking:
    image: vllm/vllm-openai:v0.11.1
    container_name: vllm-qwen3-next-80b-a3b-thinking
    restart: unless-stopped
    # Enforce eager execution to save GPU memory
    command: >
      cpatonn/Qwen3-Next-80B-A3B-Thinking-AWQ-4bit
      --gpu-memory-utilization 0.79
      --max-model-len 90000
      --max-num-batched-tokens 8192
      --kv-cache-dtype fp8
      --tensor-parallel-size 2
      --max-num-seqs 10
      --enforce-eager 
      --enable-chunked-prefill
      --enable-sleep-mode 
      --enable-auto-tool-choice 
      --tool-call-parser hermes
      --reasoning-parser qwen3
    ports:
      - "8003:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ../vllm-logging.json:/logs/logging.json:ro
      - ../logs/qwen3-next-80b-a3b-thinking:/logs
      - ~/.cache/vllm:/root/.cache/vllm             # Persist vllm cache
      - ~/.cache/triton:/root/.triton/cache         # Persist Triton kernels
      - ~/.cache/flashinfer:/root/.cache/flashinfer # Persist FlashInfer kernels
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
      - VLLM_SERVER_DEV_MODE=1
      - CUDA_VISIBLE_DEVICES=0,1
      - VLLM_HOST_IP=127.0.0.1
      - VLLM_CONFIGURE_LOGGING=1
      - VLLM_LOGGING_CONFIG_PATH=/logs/logging.json
    ipc: host
    networks:
      - homegpt-network
